version: '2'
services:
  server:
    depends_on: []
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    environment: 
      - APP_SECRET=NotReallySecretIsItNow
      - PORT=4444
      - OAUTH_ROLE=server
    volumes:
      - ./server:/var/www/html/
      - ./shared:/var/www/shared
      - ./apache-config.conf:/etc/apache2/sites-enabled/000-default.conf

    ports:
      - "4444:4444"

  client:
    depends_on: []
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    environment: 
      - OAUTH_ROLE=client
      - PORT=4443
    volumes:
      - ./client:/var/www/html/
      - ./shared:/var/www/shared
      - ./apache-config.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "4443:4443"